export const StateEnum = {
  AL: 'Alabama',
  AK: 'Alaska',
  AZ: 'Arizona',
  AR: 'Arkansas',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  FL: 'Florida',
  GA: 'Georgia',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VT: 'Vermont',
  VA: 'Virginia',
  WA: 'Washington',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming',
  DC: 'District of Columbia'
}

export const TimezoneEnum = {
  UTC: 'UTC',
  US_EASTERN: 'US/Eastern',
  US_CENTRAL: 'US/Central',
  US_MOUNTAIN: 'US/Mountain',
  US_PACIFIC: 'US/Pacific',
  US_ALASKA: 'US/Alaska',
  US_HAWAII: 'US/Hawaii',
  AMERICA_NEW_YORK: 'America/New_York',
  AMERICA_CHICAGO: 'America/Chicago',
  AMERICA_DENVER: 'America/Denver',
  AMERICA_LOS_ANGELES: 'America/Los_Angeles',
  AMERICA_ANCHORAGE: 'America/Anchorage',
  AMERICA_HONOLULU: 'America/Honolulu',
  EUROPE_LONDON: 'Europe/London',
  EUROPE_PARIS: 'Europe/Paris',
  EUROPE_BERLIN: 'Europe/Berlin',
  EUROPE_ROME: 'Europe/Rome',
  EUROPE_MADRID: 'Europe/Madrid',
  EUROPE_AMSTERDAM: 'Europe/Amsterdam',
  EUROPE_BRUSSELS: 'Europe/Brussels',
  EUROPE_STOCKHOLM: 'Europe/Stockholm',
  EUROPE_VIENNA: 'Europe/Vienna',
  EUROPE_DUBLIN: 'Europe/Dublin',
  EUROPE_PRAGUE: 'Europe/Prague',
  EUROPE_COPENHAGEN: 'Europe/Copenhagen',
  EUROPE_OSLO: 'Europe/Oslo',
  EUROPE_WARSAW: 'Europe/Warsaw',
  EUROPE_BUDAPEST: 'Europe/Budapest',
  EUROPE_ZURICH: 'Europe/Zurich',
  ASIA_TOKYO: 'Asia/Tokyo',
  ASIA_SHANGHAI: 'Asia/Shanghai',
  ASIA_SINGAPORE: 'Asia/Singapore',
  ASIA_HONG_KONG: 'Asia/Hong_Kong',
  ASIA_DUBAI: 'Asia/Dubai',
  ASIA_SEOUL: 'Asia/Seoul',
  AUSTRALIA_SYDNEY: 'Australia/Sydney',
  AUSTRALIA_MELBOURNE: 'Australia/Melbourne',
  AUSTRALIA_PERTH: 'Australia/Perth',
  PACIFIC_AUCKLAND: 'Pacific/Auckland'
}

export const CountryEnum = {
  UNITED_STATES: 'United States'
}

export const LanguageEnum = {
  ENGLISH: 'English',
  SPANISH: 'Spanish',
  FRENCH: 'French'
}

// Helper function to get all timezone values
export const getAllTimezones = () => Object.values(TimezoneEnum)
