version: '3.8'

services:
  adminui:
    container_name: adminui
    platform: linux/amd64
    image: oscar/adminui-amd64:v1.0.0
    ports:
      - '4100:4100'
    networks:
      - my_network
    environment:
      API_URL: ${API_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NODE_ENV: production

  oscarapi:
    container_name: oscarapi
    platform: linux/amd64
    image: oscar/api-amd64:v1.0.0
    ports:
      - '4200:4200'
    networks:
      - my_network
    command:
      - /bin/sh
      - -c
      - |
        uvicorn app.main:app --host 0.0.0.0 --port 4200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  oscarfabric:
    container_name: oscarfabric
    platform: linux/amd64
    image: oscar/fabric-amd64:v1.0.0
    ports:
      - '5200:5200'
    networks:
      - my_network
    command:
      - /bin/zsh
      - -c
      - |
        /home/splunk/.local/bin/uvicorn app.main:app --host 0.0.0.0 --port 5200
    volumes:
      - ./src/fabfile:/home/splunk/fabfile
      - ./src/fabric.yml:/home/splunk/fabric.yml
      - ./src/utils:/home/splunk/utils

networks:
  my_network:
    name: my_network
