version: '3.8'

services:
  adminui:
    container_name: adminui
    platform: linux/amd64
    image: oscar/adminui-amd64:v1.0.0
    ports:
      - '3000:3000'
    networks:
      - my_network
    environment:
      API_URL: ${API_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      GITHUB_ID: ${GITHUB_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
      MONGODB_URI: ${MONGODB_URI}
      NODE_ENV: production

networks:
  my_network:
    name: my_network
